#pragma once
#include "stdafx.h"

#define CHARACTER_SLOT "MP0_"

__forceinline void UnlockAll()
{
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_ABILITY_1_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_ABILITY_2_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_ABILITY_3_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_WEAP_UNLOCKED"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_WEAP_UNLOCKED2"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_WEAP_ADDON_1_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_WEAP_ADDON_2_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_WEAP_ADDON_3_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_WEAP_ADDON_4_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_WEAP_UNLOCKED"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_WEAP_UNLOCKED2"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_WEAP_ADDON_1_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_WEAP_ADDON_2_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_WEAP_ADDON_3_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_WEAP_ADDON_4_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_WEAP_ADDON_5_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_HAIRCUT_1_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_HEALTH_1_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_HEALTH_2_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_CREWUNLOCK_1_FM_EQUIP"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_CREWUNLOCK_2_FM_EQUIP"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_CREWUNLOCK_3_FM_EQUIP"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_CREWUNLOCK_4_FM_EQUIP"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_HEIST_1_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_KIT_1_FM_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_KIT_2_FM_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_KIT_3_FM_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_KIT_4_FM_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_KIT_5_FM_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_KIT_6_FM_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_KIT_7_FM_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_KIT_8_FM_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_KIT_9_FM_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_KIT_10_FM_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_KIT_11_FM_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_KIT_12_FM_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_ABILITY_1_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_ABILITY_2_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_ABILITY_3_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CLOTHES_1_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CLOTHES_2_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CLOTHES_3_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CLOTHES_4_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CLOTHES_5_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CLOTHES_6_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CLOTHES_7_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CLOTHES_8_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CLOTHES_9_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CLOTHES_10_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CLOTHES_11_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_VEHICLE_1_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_VEHICLE_2_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_0"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_1"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_2"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_3"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_4"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_5"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_6"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_7"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_8"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_9"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_10"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_11"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"TATTOO_FM_UNLOCKS_12"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"RANKAP_UNLK_0"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"RANKAP_UNLK_1"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"RANKAP_UNLK_2"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"RANKAP_UNLK_3"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_CREWUNLOCK_1_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"UNLOCK_RACE_HIPSTER_TSHIRT"), TRUE, TRUE);
	STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"UNLOCK_DM_HIPSTER_TSHIRT"), TRUE, TRUE);
	STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"UNLOCK_HIPSTER_TSHIRT_DOG"), TRUE, TRUE);
	STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"UNLOCK_HIPSTER_TSHIRT_VINYL"), TRUE, TRUE);
	STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"UNLOCK_HIPSTER_TSHIRT_MESS"), TRUE, TRUE);
}

__forceinline void UnlockLSC()
{
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"RACES_WON"), 50, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CARMOD_1_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CARMOD_2_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CARMOD_3_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CARMOD_4_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CARMOD_5_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CARMOD_6_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHAR_FM_CARMOD_7_UNLCK"), 0xFFFFFFFF, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"NUMBER_SLIPSTREAMS_IN_RACE"), 110, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"NUMBER_TURBO_STARTS_IN_RACE"), 90, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"USJS_FOUND"), 50, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"USJS_COMPLETED"), 50, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"MPPLY_TIMES_RACE_BEST_LAP"), 101, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"AWD_FMRALLYWONDRIVE"), 2, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"AWD_FMWINSEARACE"), 2, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"AWD_FMWINAIRRACE"), 2, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"AWD_FM_RACES_FASTEST_LAP"), 101, TRUE);
}

__forceinline void ClearAccount() //We can only change stats that are not ServerAuthoritative="true" in mpstatssetup.xml.
{
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CHEAT_BITSET"), 0, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"BAD_SPORT_BITSET"), 0, TRUE);
	STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MPPLY_IS_HIGH_EARNER"), FALSE, TRUE);
	STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MPPLY_IS_CHEATER"), FALSE, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_IS_CHEATER_TIME"), 0, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_WAS_I_BAD_SPORT"), 0, TRUE);
	STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MPPLY_OVERALL_BADSPORT"), 0, TRUE);
	STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY("MPPLY_OVERALL_CHEAT"), 0, TRUE);
	STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MPPLY_CHAR_IS_BADSPORT"), FALSE, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_BECAME_BADSPORT_NUM"), 0, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_BECAME_CHEATER_NUM"), 0, TRUE);
	Any date[12]; //Should be enough.
	memset(&date, 0, sizeof(date));
	STATS::STAT_SET_DATE(GAMEPLAY::GET_HASH_KEY("MPPLY_BECAME_CHEATER_DT"), &date[0], 7, TRUE);
	STATS::STAT_SET_DATE(GAMEPLAY::GET_HASH_KEY("MPPLY_BECAME_BADSPORT_DT"), &date[0], 7, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_DESTROYED_PVEHICLES"), 0, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_BADSPORT_MESSAGE"), 0, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_KILLS_PLAYERS_CHEATER"), 69, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_DEATHS_PLAYERS_CHEATER"), 420, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_LAST_REPORT_PENALTY"), 0, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_LAST_COMMEND_PENALTY"), 0, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_LAST_REPORT_RESTORE"), 0, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_LAST_COMMEND_RESTORE"), 0, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_REPORT_STRENGTH"), 32, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_COMMEND_STRENGTH"), 32, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_VOTED_OUT"), 0, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_VOTED_OUT_DELTA"), 0, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_VOTED_OUT_QUIT"), 0, TRUE);
	STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MPPLY_WAS_I_BAD_SPORT"), FALSE, TRUE);
	STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY("MPPLY_WAS_I_CHEATER"), FALSE, TRUE);
}

__forceinline void MaxStats()
{
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"SCRIPT_INCREASE_STAM"), 100, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"SCRIPT_INCREASE_STRN"), 100, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"SCRIPT_INCREASE_LUNG"), 100, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"SCRIPT_INCREASE_DRIV"), 100, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"SCRIPT_INCREASE_FLY"), 100, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"SCRIPT_INCREASE_SHO"), 100, TRUE);
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"SCRIPT_INCREASE_STL"), 100, TRUE);
}

__forceinline void MaxSnacks() //MAX MEMES
{
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"NO_BOUGHT_YUM_SNACKS"), 30, TRUE); //P's & Q's
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"NO_BOUGHT_HEALTH_SNACKS"), 15, TRUE); //EgoChaser
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"NO_BOUGHT_EPIC_SNACKS"), 5, TRUE); //Meteorite
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"NUMBER_OF_ORANGE_BOUGHT"), 10, TRUE); //eCola
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"NUMBER_OF_BOURGE_BOUGHT"), 10, TRUE); //Piﬂwasser #memewasser
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"CIGARETTES_BOUGHT"), 20, TRUE); //Cigarettes
}

__forceinline void ChangeApprence()
{
	STATS::STAT_SET_BOOL(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"FM_CHANGECHAR_ASKED"), FALSE, TRUE);
}

__forceinline void MakeEventCarPurchaseable(Hash vehicleModel)
{
	STATS::STAT_SET_INT(GAMEPLAY::GET_HASH_KEY("MPPLY_VEHICLE_ID_ADMIN_WEB"), vehicleModel, TRUE);
}

__forceinline void ClearMentalState()
{
	STATS::STAT_SET_FLOAT(GAMEPLAY::GET_HASH_KEY(CHARACTER_SLOT"PLAYER_MENTAL_STATE"), 0.0f, TRUE);
}

__forceinline void LogIntStat(char* chStat, bool bShowAsHex = false)
{
	int value = NULL;
	STATS::STAT_GET_INT(GAMEPLAY::GET_HASH_KEY(chStat), &value, -1);
	if (bShowAsHex)
		Log::Msg("%s: (0x%08X)", chStat, value);
	else
		Log::Msg("%s: (%i)", chStat, value);
}

__forceinline void LogBoolStat(char* chStat)
{
	BOOL value = FALSE;
	STATS::STAT_GET_BOOL(GAMEPLAY::GET_HASH_KEY(chStat), &value, -1);
	Log::Msg("%s: (%s)", chStat, value ? "TRUE" : "FALSE");
}

__forceinline void LogFloatStat(char* chStat)
{
	float value = 0.0f;
	STATS::STAT_GET_FLOAT(GAMEPLAY::GET_HASH_KEY(chStat), &value, -1);
	Log::Msg("%s: (%f)", chStat, value);
}

__forceinline void LogIntStatToScreen(char* chStat, int index = 0, bool bShowAsHex = false)
{
	int value = NULL;
	STATS::STAT_GET_INT(GAMEPLAY::GET_HASH_KEY(chStat), &value, -1);
	if (bShowAsHex)
		Log::ToScreen(index, "%s: (0x%08X)", chStat, value);
	else
		Log::ToScreen(index, "%s: (%i)", chStat, value);
}

__forceinline void LogBoolStatToScreen(char* chStat, int index = 0)
{
	BOOL value = FALSE;
	STATS::STAT_GET_BOOL(GAMEPLAY::GET_HASH_KEY(chStat), &value, -1);
	Log::ToScreen(index, "%s: (%s)", chStat, value ? "TRUE" : "FALSE");
}

__forceinline void LogFloatStatToScreen(char* chStat, int index = 0)
{
	float value = 0.0f;
	STATS::STAT_GET_FLOAT(GAMEPLAY::GET_HASH_KEY(chStat), &value, -1);
	Log::ToScreen(index, "%s: (%.2f)", chStat, value);
}