#pragma once

enum SeatPositions
{
	SEAT_DRIVER = -1,
	SEAT_PASSENGER = 0,
	SEAT_BACKDRIVER = 1,
	SEAT_BACKPASSENGER = 2
};

enum WheelTypes
{
	WHEEL_TYPE_STOCK = -1,
	WHEEL_TYPE_SPORT,
	WHEEL_TYPE_MUSCLE,
	WHEEL_TYPE_LOWRIDER,
	WHEEL_TYPE_SUV,
	WHEEL_TYPE_OFFROAD,
	WHEEL_TYPE_TUNER,
	WHEEL_TYPE_BIKEWHEELS,
	WHEEL_TYPE_HIGHEND
};

enum TunerTypes
{
	WHEEL_TUNER_STOCK = -1,
	WHEEL_TUNER_COSMO,
	WHEEL_TUNER_SUPERMESH,
	WHEEL_TUNER_OUTSIDER,
	WHEEL_TUNER_ROLLAS,
	WHEEL_TUNER_DRIFFMEISTER,
	WHEEL_TUNER_SLICER,
	WHEEL_TUNER_ELQUATRO,
	WHEEL_TUNER_DUBBED,
	WHEEL_TUNER_FIVESTAR,
	WHEEL_TUNER_SLIDEWAYS,
	WHEEL_TUNER_APEX,
	WHEEL_TUNER_STANCEDEG,
	WHEEL_TUNER_COUNTERSTEER,
	WHEEL_TUNER_ENDOV1,
	WHEEL_TUNER_ENDOV2DISH,
	WHEEL_TUNER_GUPPEZ,
	WHEEL_TUNER_CHOKADORI,
	WHEEL_TUNER_CHICANE,
	WHEEL_TUNER_SAISOKU,
	WHEEL_TUNER_DISHEDEIGHT,
	WHEEL_TUNER_FUJIWARA,
	WHEEL_TUNER_ZOKUSHA,
	WHEEL_TUNER_BATTLEVLLL,
	WHEEL_TUNER_RALLYMASTER
};

enum HighEndWheels
{
	WHEEL_HIGHEND_STOCK = -1,
	WHEEL_HIGHEND_SHADOW,
	WHEEL_HIGHEND_HYPHER,
	WHEEL_HIGHEND_BLADE,
	WHEEL_HIGHEND_DIAMOND,
	WHEEL_HIGHEND_SUPAGEE,
	WHEEL_HIGHEND_CHROMATICZ,
	WHEEL_HIGHEND_MERCIECHLIP,
	WHEEL_HIGHEND_OBEYRS,
	WHEEL_HIGHEND_GTCHROME,
	WHEEL_HIGHEND_CHEETAHR,
	WHEEL_HIGHEND_SOLAR,
	WHEEL_HIGHEND_SPLITTEN,
	WHEEL_HIGHEND_DASHVIP,
	WHEEL_HIGHEND_LOZSPEEDTEN,
	WHEEL_HIGHEND_CARBONINFERNO,
	WHEEL_HIGHEND_CARBONSHADOW,
	WHEEL_HIGHEND_CARBONZ,
	WHEEL_HIGHEND_CARBONSOLAR,
	WHEEL_HIGHEND_CARBONCHEETAHR,
	WHEEL_HIGHEND_CARBONSRACER
};

enum LowriderWheels
{
	WHEEL_LOWRIDER_STOCK = -1,
	WHEEL_LOWRIDER_FLARE,
	WHEEL_LOWRIDER_WIRED,
	WHEEL_LOWRIDER_TRIPLEGOLDS,
	WHEEL_LOWRIDER_BIGWORM,
	WHEEL_LOWRIDER_SEVENFIVES,
	WHEEL_LOWRIDER_SPLITSIX,
	WHEEL_LOWRIDER_FRESHMESH,
	WHEEL_LOWRIDER_LEADSLED,
	WHEEL_LOWRIDER_TURBINE,
	WHEEL_LOWRIDER_SUPERFIN,
	WHEEL_LOWRIDER_CLASSICROD,
	WHEEL_LOWRIDER_DOLLAR,
	WHEEL_LOWRIDER_DUKES,
	WHEEL_LOWRIDER_LOWFIVE,
	WHEEL_LOWRIDER_GOOCH,
};

enum MuscleWheels
{
	WHEEL_MUSCLE_STOCK = -1,
	WHEEL_MUSCLE_CLASSICFIVE,
	WHEEL_MUSCLE_DUKES,
	WHEEL_MUSCLE_MUSCLEFREAK,
	WHEEL_MUSCLE_KRACKA,
	WHEEL_MUSCLE_AZREA,
	WHEEL_MUSCLE_MECHA,
	WHEEL_MUSCLE_BLACKTOP,
	WHEEL_MUSCLE_DRAGSPL,
	WHEEL_MUSCLE_REVOLVER,
	WHEEL_MUSCLE_CLASSICROD,
	WHEEL_MUSCLE_FAIRLRE,
	WHEEL_MUSCLE_SPOONER,
	WHEEL_MUSCLE_FIVESTAR,
	WHEEL_MUSCLE_OLDSCHOOL,
	WHEEL_MUSCLE_ELJEFE,
	WHEEL_MUSCLE_DODMAN,
	WHEEL_MUSCLE_SIXGUN,
	WHEEL_MUSCLE_MERCENARY
};

enum OffroadWheels
{
	WHEEL_OFFROAD_STOCK = -1,
	WHEEL_OFFROAD_RAIDER,
	WHEEL_OFFROAD_MUDSLINGER,
	WHEEL_OFFROAD_NEVIS,
	WHEEL_OFFROAD_CAIRNGORM,
	WHEEL_OFFROAD_AMAZON,
	WHEEL_OFFROAD_CHALLENGER,
	WHEEL_OFFROAD_DUNEBASHER,
	WHEEL_OFFROAD_FIVESTAR,
	WHEEL_OFFROAD_ROCKCRAWLER,
	WHEEL_OFFROAD_MILSPECSTEELIE
};

enum SportWheels
{
	WHEEL_SPORT_STOCK = -1,
	WHEEL_SPORT_INFERNO,
	WHEEL_SPORT_DEEPFIVE,
	WHEEL_SPORT_LOZSPEED,
	WHEEL_SPORT_DIAMONDCUT,
	WHEEL_SPORT_CHRONO,
	WHEEL_SPORT_FEROCCIRR,
	WHEEL_SPORT_FIFTYNINE,
	WHEEL_SPORT_MERCIE,
	WHEEL_SPORT_SYNTHETICZ,
	WHEEL_SPORT_ORGANICTYPED,
	WHEEL_SPORT_ENDOV1,
	WHEEL_SPORT_DUPER7,
	WHEEL_SPORT_UZER,
	WHEEL_SPORT_GROUNDRIDE,
	WHEEL_SPORT_SRACER,
	WHEEL_SPORT_VENUM,
	WHEEL_SPORT_COSMO,
	WHEEL_SPORT_DASHVIP,
	WHEEL_SPORT_ICEKID,
	WHEEL_SPORT_RUFFWELD,
	WHEEL_SPORT_WANGENMASTER,
	WHEEL_SPORT_SUPERFIVE,
	WHEEL_SPORT_ENDOV2,
	WHEEL_SPORT_SLITSIX
};

enum SUVWheels
{
	WHEEL_SUV_STOCK = -1,
	WHEEL_SUV_VIP,
	WHEEL_SUV_BENEFACTOR,
	WHEEL_SUV_COSMO,
	WHEEL_SUV_BIPPU,
	WHEEL_SUV_ROYALSIX,
	WHEEL_SUV_FAGORME,
	WHEEL_SUV_DELUXE,
	WHEEL_SUV_ICEDOUT,
	WHEEL_SUV_COGNSCENTI,
	WHEEL_SUV_LOZSPEEDTEN,
	WHEEL_SUV_SUPERNOVA,
	WHEEL_SUV_OBEYRS,
	WHEEL_SUV_LOZSPEEDBALLER,
	WHEEL_SUV_EXTRAVAGANZO,
	WHEEL_SUV_SPLITSIX,
	WHEEL_SUV_EMPOWERED,
	WHEEL_SUV_SUNRISE,
	WHEEL_SUV_DASHVIP,
	WHEEL_SUV_CUTTER
};

enum BikeWheels
{
	WHEEL_BIKE_STOCK = -1,
	WHEEL_BIKE_SPEEDWAY,
	WHEEL_BIKE_STREETSPECIAL,
	WHEEL_BIKE_RACER,
	WHEEL_BIKE_TRACKSTAR,
	WHEEL_BIKE_OVERLORD,
	WHEEL_BIKE_TRIDENT,
	WHEEL_BIKE_TRIPLETHREAT,
	WHEEL_BIKE_STILLETO,
	WHEEL_BIKE_WIRES,
	WHEEL_BIKE_BOBBER,
	WHEEL_BIKE_SOLIDUS,
	WHEEL_BIKE_ICESHIELD,
	WHEEL_BIKE_LOOPS
};

enum VehicleModTypes
{
	MOD_SPOILER,
	MOD_FRONTBUMPER,
	MOD_REARBUMPER,
	MOD_SIDESKIRT,
	MOD_EXHAUST,
	MOD_CHASSIS, //Or roll cage
	MOD_GRILLE,
	MOD_HOOD,
	MOD_FENDER,
	MOD_RIGHTFENDER,
	MOD_ROOF,
	MOD_ENGINE,
	MOD_BRAKES,
	MOD_TRANSMISSION,
	MOD_HORNS,
	MOD_SUSPENSION,
	MOD_ARMOR,
	MOD_TURBO = 18,
	MOD_TIRESMOKE = 20,
	MOD_XENONLIGHTS = 22,
	MOD_FRONTWHEELS,
	MOD_BACKWHEELS //Bikes only
};

enum VehicleModHorns
{
	HORN_STOCK = -1,
	HORN_TRUCK,
	HORN_POLICE,
	HORN_CLOWN,
	HORN_MUSICAL1,
	HORN_MUSICAL2,
	HORN_MUSICAL3,
	HORN_MUSICAL4,
	HORN_MUSICAL5,
	HORN_SADTROMBONE,
	HORN_CALSSICAL1,
	HORN_CALSSICAL2,
	HORN_CALSSICAL3,
	HORN_CALSSICAL4,
	HORN_CALSSICAL5,
	HORN_CALSSICAL6,
	HORN_CALSSICAL7,
	HORN_SCALEDO,
	HORN_SCALERE,
	HORN_SCALEMI,
	HORN_SCALEFA,
	HORN_SCALESOL,
	HORN_SCALELA,
	HORN_SCALETI,
	HORN_SCALEDO_HIGH,
	HORN_JAZZ1,
	HORN_JAZZ2,
	HORN_JAZZ3,
	HORN_JAZZLOOP,
	HORN_STARSPANGBAN1,
	HORN_STARSPANGBAN2,
	HORN_STARSPANGBAN3,
	HORN_STARSPANGBAN4
};

enum VehicleAddonLevel
{
	MOD_INDEX_OFF = -1,
	MOD_INDEX_ONE, //To determine mod index, look at the mod menu in LSC, the first item is MOD_INDEX_ONE. Count down to the item you want. Stock counts as OFF.
	MOD_INDEX_TWO,
	MOD_INDEX_THREE,
	MOD_INDEX_FOUR,
	MOD_INDEX_FIVE,
	MOD_INDEX_SIX,
	MOD_INDEX_SEVEN,
	MOD_INDEX_EIGHT,
	MOD_INDEX_NINE
};

enum NeonLightLocations
{
	NEON_LEFT,
	NEON_RIGHT,
	NEON_FRONT,
	NEON_BACK
};

enum VehicleColors
{
	COLOR_RANDOM = -1,
	COLOR_METALLIC_BLACK,
	COLOR_METALLIC_GRAPHITE_BLACK,
	COLOR_METALLIC_BLACK_STEAL,
	COLOR_METALLIC_DARK_SILVER,
	COLOR_METALLIC_SILVER,
	COLOR_METALLIC_BLUE_SILVER,
	COLOR_METALLIC_STEEL_GRAY,
	COLOR_METALLIC_SHADOW_SILVER,
	COLOR_METALLIC_STONE_SILVER,
	COLOR_METALLIC_MIDNIGHT_SILVER,
	COLOR_METALLIC_GUN_METAL,
	COLOR_METALLIC_ANTHRACITE_GREY,
	COLOR_MATTE_BLACK,
	COLOR_MATTE_GRAY,
	COLOR_MATTE_LIGHT_GREY,
	COLOR_UTIL_BLACK,
	COLOR_UTIL_BLACK_POLY,
	COLOR_UTIL_DARK_SILVER,
	COLOR_UTIL_SILVER,
	COLOR_UTIL_GUN_METAL,
	COLOR_UTIL_SHADOW_SILVER,
	COLOR_WORN_BLACK,
	COLOR_WORN_GRAPHITE,
	COLOR_WORN_SILVER_GREY,
	COLOR_WORN_SILVER,
	COLOR_WORN_BLUE_SILVER,
	COLOR_WORN_SHADOW_SILVER,
	COLOR_METALLIC_RED,
	COLOR_METALLIC_TORINO_RED,
	COLOR_METALLIC_FORMULA_RED,
	COLOR_METALLIC_BLAZE_RED,
	COLOR_METALLIC_GRACEFUL_RED,
	COLOR_METALLIC_GARNET_RED,
	COLOR_METALLIC_DESERT_RED,
	COLOR_METALLIC_CABERNET_RED,
	COLOR_METALLIC_CANDY_RED,
	COLOR_METALLIC_SUNRISE_ORANGE,
	COLOR_METALLIC_CLASSIC_GOLD,
	COLOR_METALLIC_ORANGE,
	COLOR_MATTE_RED,
	COLOR_MATTE_DARK_RED,
	COLOR_MATTE_ORANGE,
	COLOR_MATTE_YELLOW,
	COLOR_UTIL_RED,
	COLOR_UTIL_BRIGHT_RED,
	COLOR_UTIL_GARNET_RED,
	COLOR_WORN_RED,
	COLOR_WORN_GOLDEN_RED,
	COLOR_WORN_DARK_RED,
	COLOR_METALLIC_DARK_GREEN,
	COLOR_METALLIC_RACING_GREEN,
	COLOR_METALLIC_SEA_GREEN,
	COLOR_METALLIC_OLIVE_GREEN,
	COLOR_METALLIC_BRIGHT_GREEN,
	COLOR_METALLIC_GASOLINE_GREEN,
	COLOR_MATTE_LIME_GREEN,
	COLOR_UTIL_DARK_GREEN,
	COLOR_WORN_DARK_GREEN,
	COLOR_WORN_SEA_WASH,
	COLOR_METALLIC_MIDNIGHT_BLUE,
	COLOR_METALLIC_DARK_BLUE,
	COLOR_METALLIC_GALAXY_BLUE,
	COLOR_DARK_BLUE,
	COLOR_SAXON_BLUE,
	COLOR_BLUE,
	COLOR_METALLIC_MARINER_BLUE,
	COLOR_METALLIC_HARBOR_BLUE,
	COLOR_METALLIC_DIAMOND_BLUE,
	COLOR_METALLIC_SURF_BLUE,
	COLOR_METALLIC_NAUTICAL_BLUE,
	COLOR_METALLIC_ULTRA_BLUE,
	COLOR_METALLIC_BRIGHT_BLUE,
	COLOR_METALLIC_PURPLE_BLUE,
	COLOR_METALLIC_RACING_BLUE,
	COLOR_METALLIC_LIGHT_BLUE,
	COLOR_UTIL_DARK_BLUE,
	COLOR_UTIL_MIDNIGHT_BLUE,
	COLOR_UTIL_BLUE,
	COLOR_UTIL_SEA_FOAM_BLUE,
	COLOR_UIIL_LIGHTNING_BLUE,
	COLOR_UTIL_MAUI_BLUE_POLY,
	COLOR_UTIL_BRIGHT_BLUE,
	COLOR_MATTE_DARK_BLUE,
	COLOR_MATTE_BLUE,
	COLOR_MATTE_MIDNIGHT_BLUE,
	COLOR_WORN_DARK_BLUE,
	COLOR_WORN_BLUE,
	COLOR_WORN_LIGHT_BLUE,
	COLOR_METALLIC_TAXI_YELLOW,
	COLOR_METALLIC_RACE_YELLOW,
	COLOR_METALLIC_BRONZE,
	COLOR_METALLIC_YELLOW_BIRD,
	COLOR_METALLIC_LIME,
	COLOR_METALLIC_CHAMPAGNE,
	COLOR_METALLIC_PUEBLO_BEIGE,
	COLOR_METALLIC_DARK_IVORY,
	COLOR_METALLIC_CHOCO_BROWN,
	COLOR_METALLIC_GOLDEN_BROWN,
	COLOR_METALLIC_LIGHT_BROWN,
	COLOR_METALLIC_STRAW_BEIGE,
	COLOR_METALLIC_MOSS_BROWN,
	COLOR_METALLIC_BISTON_BROWN,
	COLOR_METALLIC_BEECHWOOD,
	COLOR_METALLIC_DARK_BEECHWOOD,
	COLOR_METALLIC_CHOCO_ORANGE,
	COLOR_METALLIC_BEACH_SAND,
	COLOR_METALLIC_SUN_BLEECHED_SAND,
	COLOR_METALLIC_CREAM,
	COLOR_UTIL_BROWN,
	COLOR_UTIL_MEDIUM_BROWN,
	COLOR_UTIL_LIGHT_BROWN,
	COLOR_METALLIC_WHITE,
	COLOR_METALLIC_FROST_WHITE,
	COLOR_WORN_HONEY_BEIGE,
	COLOR_WORN_BROWN,
	COLOR_WORN_DARK_BROWN,
	COLOR_WORN_STRAW_BEIGE,
	COLOR_BRUSHED_STEEL,
	COLOR_BRUSHED_BLACK_STEEL,
	COLOR_BRUSHED_ALUMINIUM,
	COLOR_CHROME,
	COLOR_WORN_OFF_WHITE,
	COLOR_UTIL_OFF_WHITE,
	COLOR_WORN_ORANGE,
	COLOR_WORN_LIGHT_ORANGE,
	COLOR_METALLIC_SECURICOR_GREEN,
	COLOR_WORN_TAXI_YELLOW,
	COLOR_POLICE_CAR_BLUE,
	COLOR_MATTE_GREEN,
	COLOR_MATTE_BROWN,
	COLOR_WORN_ORANGE2,
	COLOR_MATTE_WHITE,
	COLOR_WORN_WHITE,
	COLOR_WORN_OLIVE_ARMY_GREEN,
	COLOR_PURE_WHITE,
	COLOR_HOT_PINK,
	COLOR_SALMON_PINK,
	COLOR_METALLIC_VERMILLION_PINK,
	COLOR_ORANGE,
	COLOR_GREEN,
	COLOR_FLOURSCENT_BLUE,
	COLOR_METTALIC_BLACK_BLUE,
	COLOR_METALLIC_BLACK_PURPLE,
	COLOR_METALLIC_BLACK_RED,
	COLOR_HUNTER_GREEN,
	COLOR_METALLIC_PURPLE,
	COLOR_METAILLIC_V_DARK_BLUE,
	COLOR_MODSHOP_BLACK1,
	COLOR_MATTE_PURPLE,
	COLOR_MATTE_DARK_PURPLE,
	COLOR_METALLIC_LAVA_RED,
	COLOR_MATTE_FOREST_GREEN,
	COLOR_MATTE_OLIVE_DRAB,
	COLOR_MATTE_DESERT_BROWN,
	COLOR_MATTE_DESERT_TAN,
	COLOR_MATTE_FOILAGE_GREEN,
	COLOR_DEFAULT_ALLOY_COLOR,
	COLOR_EPSILON_BLUE
};

enum PlateTextIndexs
{
	PLATE_BLUEONWHITE1,
	PLATE_YELLOWONBLACK,
	PLATE_YELLOWONBLUE,
	PLATE_BLUEONWHITE2,
	PLATE_BLUEONWHITE3,
	PLATE_YANKTON
};

enum WindowTints //m8 do you even int tint?
{
	WINDOWTINT_NONE,
	WINDOWTINT_BLACK,
	WINDOWTINT_DARKSMOKE,
	WINDOWTINT_LIGHTSMOKE,
	WINDOWTINT_STOCK,
	WINDOWTINT_LIMO,
	WINDOWTINT_GREEN
};

#define NEON_COLOR_WHITE 222, 222, 255
#define NEON_COLOR_BLUE 2, 21, 255
#define NEON_COLOR_ELECTRICBLUE 3, 83, 255
#define NEON_COLOR_MINTGREEN 0, 255, 140
#define NEON_COLOR_LIMEGREEN 94, 255, 1
#define NEON_COLOR_YELLOW 255, 255, 0
#define NEON_COLOR_GOLDENSHOWER 255, 150, 5
#define NEON_COLOR_ORANGE 255, 62, 0
#define NEON_COLOR_RED 255, 1, 1
#define NEON_COLOR_PONYPINK 255, 50, 100 //Fag
#define NEON_COLOR_HOTPINK 255, 5, 190
#define NEON_COLOR_PURPLE 35, 1, 255
#define NEON_COLOR_BACKLIGHT 15, 3, 255

#define TIRESMOKE_COLOR_WHITE 255, 255, 255
#define TIRESMOKE_COLOR_BLACK 20, 20, 20
#define TIRESMOKE_COLOR_BLUE 0, 174, 239
#define TIRESMOKE_COLOR_YELLOW 252, 238, 0
#define TIRESMOKE_COLOR_PURPLE 100, 79, 142
#define TIRESMOKE_COLOR_ORANGE 255, 127, 0
#define TIRESMOKE_COLOR_GREEN 114, 204, 114
#define TIRESMOKE_COLOR_RED 226, 6, 6
#define TIRESMOKE_COLOR_PINK 203, 54, 148
#define TIRESMOKE_COLOR_BROWN 180, 130, 97
#define TIRESMOKE_COLOR_PATRIOT 0, 0, 0